# Generated by Django 3.1.1 on 2022-01-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0002_auto_20200920_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=50)),
                ('role', models.ManyToManyField(to='user_profile.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('router', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('role', models.ManyToManyField(to='user_profile.Role')),
            ],
        ),
    ]
