# Generated by Django 3.1.1 on 2022-01-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='table',
            field=models.ManyToManyField(to='api.Table'),
        ),
    ]
