# Generated by Django 3.1.1 on 2021-05-12 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Подразделение')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Участок')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='develop.division')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Оборудование')),
                ('stock_number', models.CharField(max_length=25, verbose_name='Инвентарный номер')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='develop.division')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='develop.region')),
            ],
        ),
    ]
