# Generated by Django 3.1.1 on 2020-09-18 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True, verbose_name='Цена заявки')),
                ('payed', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True, verbose_name='Оплаченная сумма')),
                ('accountant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountant', to=settings.AUTH_USER_MODEL, verbose_name='Представитель заказчика')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postoffice.contract', verbose_name='Договор')),
                ('expert', models.ForeignKey(blank=True, help_text='Исполнитель', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expert', to=settings.AUTH_USER_MODEL)),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='postoffice.inbox', verbose_name='Входящее')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Краткое описание')),
                ('estimate', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка выполения задачи')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiator', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainWork.taskstatus', verbose_name='Статус')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriber', to=settings.AUTH_USER_MODEL, verbose_name='Потребитель')),
                ('work_flow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainWork.mainwork', verbose_name='Работа')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Краткое описание')),
                ('annex', models.FileField(blank=True, null=True, upload_to='mainWork/static', verbose_name='Приложение')),
                ('recipients', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Получатели')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Message_sender', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainWork.task', verbose_name='Задача')),
            ],
        ),
        migrations.AddField(
            model_name='mainwork',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainWork.status', verbose_name='Статус заявки'),
        ),
    ]
