# Generated by Django 3.1.1 on 2020-09-18 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SendStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Статус отправки')),
            ],
        ),
        migrations.CreateModel(
            name='TypeLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Тип письма')),
            ],
        ),
        migrations.CreateModel(
            name='TypeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Тип работы')),
            ],
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(unique=True, verbose_name='Исходящй №')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата регистрации')),
                ('title', models.CharField(max_length=100, verbose_name='Тема письма')),
                ('content', models.TextField(verbose_name='Краткое содержание')),
                ('annex', models.FileField(blank=True, null=True, upload_to='Outbox/')),
                ('notice', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Sender', to=settings.AUTH_USER_MODEL)),
                ('type_letter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='postoffice.typeletter', verbose_name='Тип документа')),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(unique=True, verbose_name='Входящй №')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата регистрации')),
                ('title', models.CharField(max_length=100, verbose_name='Тема письма')),
                ('content', models.TextField(verbose_name='Краткое содержание')),
                ('annex', models.FileField(blank=True, null=True, upload_to='Inbox/', verbose_name='Вложение')),
                ('notice', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.organisation', verbose_name='Организация-отправитель')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='Зарегистрировал')),
                ('send_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='postoffice.sendstatus', verbose_name='Статус получения')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('type_letter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='postoffice.typeletter', verbose_name='Тип документа')),
                ('type_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='postoffice.typework', verbose_name='Тип работы')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.SmallIntegerField(unique=True, verbose_name='Номер договора')),
                ('date', models.DateField(verbose_name='Дата заключения')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость договора')),
                ('external_num', models.CharField(max_length=25, verbose_name='Внешний номер договора')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisation.organisation', verbose_name='Заказчик')),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='postoffice.inbox')),
                ('type_work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='postoffice.typework', verbose_name='Тип работы')),
            ],
        ),
    ]
