# Generated by Django 3.1.1 on 2020-10-07 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_auto_20200930_2137'),
        ('postoffice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.object', verbose_name='Объект контроля'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='inbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='postoffice.inbox', verbose_name='Основание заключения договора'),
        ),
    ]
