# Generated by Django 3.1.1 on 2020-10-26 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postoffice', '0002_auto_20201007_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Статус договора')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='postoffice.contractstatus', verbose_name='Статус договора'),
            preserve_default=False,
        ),
    ]
