# Generated by Django 3.1.1 on 2021-02-04 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_auto_20210202_2216'),
        ('postoffice', '0003_auto_20201026_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='postoffice.contract')),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.form')),
            ],
        ),
    ]
