# Generated by Django 3.1.1 on 2021-02-10 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_auto_20210210_1331'),
        ('postoffice', '0004_workrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='object',
        ),
        migrations.AddField(
            model_name='workrequest',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.object'),
        ),
    ]
