# Generated by Django 3.1.1 on 2021-02-19 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0009_remove_protocol_object_exam'),
        ('postoffice', '0007_workrequest_protocol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workrequest',
            name='protocol',
        ),
        migrations.CreateModel(
            name='ObjRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisation.object')),
                ('protocol', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='organisation.protocol')),
                ('work_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='postoffice.workrequest')),
            ],
        ),
        migrations.RemoveField(
            model_name='workrequest',
            name='object',
        ),
        migrations.AddField(
            model_name='workrequest',
            name='object',
            field=models.ManyToManyField(through='postoffice.ObjRequest', to='organisation.Object'),
        ),
    ]
