# Generated by Django 3.1.1 on 2021-02-19 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0009_remove_protocol_object_exam'),
        ('postoffice', '0009_auto_20210219_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objrequest',
            name='protocol',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.protocol'),
        ),
    ]
