# Generated by Django 3.1.1 on 2020-09-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_remove_organisation_in_head_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='phone',
            field=models.BigIntegerField(blank=True, help_text='Телефон', null=True),
        ),
    ]
