# Generated by Django 3.1.1 on 2021-02-02 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_auto_20200930_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя поля')),
            ],
        ),
        migrations.CreateModel(
            name='DefectList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=255, verbose_name='Документ')),
                ('point', models.CharField(max_length=25, verbose_name='Номер пункта')),
                ('phrasing', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Документ')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Контролируемый элемент')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование формы')),
            ],
        ),
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Программа обследования')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Вид контроля')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование столбца')),
                ('align', models.SmallIntegerField(blank=True, choices=[(0, 'none'), (1, 'start'), (2, 'center'), (3, 'end')], null=True)),
                ('type', models.SmallIntegerField(blank=True, choices=[(0, 'none'), (1, 'bool'), (2, 'rows_num'), (3, 'select'), (4, 'actions')], null=True)),
                ('sortable', models.BooleanField(blank=True, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование данных столбца')),
                ('width', models.CharField(blank=True, max_length=5, null=True, verbose_name='Относительная ширина столбца')),
                ('editable', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование строки')),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Неизменное содержимое ячейки')),
                ('name', models.CharField(max_length=255)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisation.row')),
            ],
        ),
        migrations.AlterField(
            model_name='object',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.organisation'),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование таблицы')),
                ('form', models.ManyToManyField(to='organisation.Form')),
            ],
        ),
        migrations.CreateModel(
            name='SellValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Содержимое ячейки')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisation.protocol')),
                ('sell', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisation.sell')),
            ],
        ),
        migrations.CreateModel(
            name='SelectChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=25)),
                ('value', models.CharField(max_length=25)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisation.header')),
            ],
        ),
        migrations.AddField(
            model_name='row',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisation.table'),
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=25, verbose_name='Номер пункта')),
                ('phrasing', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisation.document')),
            ],
        ),
        migrations.AddField(
            model_name='header',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisation.table'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.form'),
        ),
    ]
