# Generated by Django 3.1.1 on 2021-02-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_auto_20210210_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='legal_address',
            field=models.CharField(blank=True, help_text='Юридический адрес', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='post_address',
            field=models.CharField(blank=True, help_text='Почтовый адрес', max_length=500, null=True),
        ),
    ]
