# Generated by Django 3.1.1 on 2021-02-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0008_auto_20210212_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocol',
            name='object_exam',
        ),
    ]
