# Generated by Django 3.1.1 on 2021-02-23 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisation', '0009_remove_protocol_object_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='organisation.organisation', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='customer_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_person', to=settings.AUTH_USER_MODEL, verbose_name='Контактное лицо заказчика'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='device_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.deviceset', verbose_name='Набор инструментов'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='num',
            field=models.CharField(max_length=25, null=True, verbose_name='Номер протокола'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner', to='organisation.organisation', verbose_name='Собственник'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='owner_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_person', to=settings.AUTH_USER_MODEL, verbose_name='Контактное лицо собственника'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='type_protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.typeprotocol', verbose_name='Тип протокола'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
