# Generated by Django 3.1.1 on 2021-03-10 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0011_auto_20210223_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rowdefects',
            name='row',
        ),
        migrations.AddField(
            model_name='rowdefects',
            name='header',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='organisation.header'),
            preserve_default=False,
        ),
    ]
