# Generated by Django 3.1.1 on 2021-03-10 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0012_auto_20210310_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rowdefects',
            name='header',
        ),
        migrations.AddField(
            model_name='rowdefects',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='organisation.table'),
            preserve_default=False,
        ),
    ]
