# Generated by Django 3.1.1 on 2021-03-13 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0014_auto_20210310_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolannex',
            name='sell_value',
        ),
        migrations.RemoveField(
            model_name='protocolannex',
            name='type',
        ),
        migrations.AddField(
            model_name='protocolannex',
            name='protocol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='organisation.protocol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocolannex',
            name='row',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.row'),
        ),
        migrations.AddField(
            model_name='protocolannex',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.table'),
        ),
    ]
