# Generated by Django 3.1.1 on 2021-03-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0015_auto_20210313_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='column',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
