# Generated by Django 3.1.1 on 2021-03-27 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0016_header_column'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocolannex',
            old_name='name',
            new_name='filename',
        ),
    ]
