# Generated by Django 3.1.1 on 2021-04-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0018_auto_20210402_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='column',
            new_name='data',
        ),
        migrations.AlterField(
            model_name='sellvalue',
            name='value',
            field=models.CharField(max_length=255, null=True, verbose_name='Содержимое ячейки'),
        ),
    ]
