# Generated by Django 3.1.1 on 2021-04-12 15:54

from django.db import migrations

def init_forms(apps, schema_editor):
    # Выбираем из базы нужную форму
    Form = apps.get_model('organisation', 'Form')
    form = Form.objects.get(name="Пассажирский лифт")

    # Выбираем привязанные к форме таблицы
    tables = form.table_set().all()
    

class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0019_auto_20210403_1017'),
    ]

    operations = [
        migrations.RunPython(init_forms),
    ]
