# Generated by Django 3.1.1 on 2021-09-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0019_auto_20210403_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Положение столбца в таблице'),
        ),
    ]
