# Generated by Django 3.1.1 on 2021-09-28 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0020_header_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='col',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.header'),
        ),
    ]
