# Generated by Django 3.1.1 on 2021-11-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0021_sell_col'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='order',
            field=models.IntegerField(null=True, verbose_name='Порядок строки в таблице'),
        ),
    ]
