# Generated by Django 3.1.1 on 2021-12-27 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0023_auto_20211227_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('form', models.FileField(upload_to='LeadForm')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisation.lead')),
            ],
        ),
    ]
