# Generated by Django 3.1.1 on 2021-12-27 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0024_leadform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.organisation'),
        ),
    ]
