# Generated by Django 3.1.1 on 2021-12-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0025_auto_20211227_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadform',
            name='name',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
