# Generated by Django 3.1.1 on 2022-01-16 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisation', '0026_auto_20211227_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
        migrations.RemoveField(
            model_name='worklift',
            name='year_of_commission',
        ),
        migrations.CreateModel(
            name='LeadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.CharField(max_length=55)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisation.lead')),
            ],
        ),
        migrations.CreateModel(
            name='FlawDetectionObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('object', models.CharField(max_length=255)),
                ('element', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisation.lead')),
            ],
        ),
        migrations.AlterField(
            model_name='lead',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.leadwork'),
        ),
    ]
