# Generated by Django 3.1.1 on 2022-02-06 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0031_auto_20220205_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadform',
            name='change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
