# Generated by Django 3.1.1 on 2022-02-06 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0033_auto_20220207_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadform',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_form', to='organisation.lead'),
        ),
        migrations.AlterField(
            model_name='leadlog',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leadlog', to='organisation.lead'),
        ),
    ]
